# echo播放器 Netlify 部署配置

[build]
# 发布目录（静态文件目录）
publish = "."

# 构建命令（如果有的话）
# command = "npm run build"

[build.environment]
# Node.js 版本
NODE_VERSION = "18"

# 网站设置
[context.production]
publish = "."

[context.deploy-preview]
publish = "."

# 重定向规则
[[redirects]]
# SPA 路由支持（如果需要的话）
from = "/*"
to = "/index.html"
status = 200
conditions = {Role = ["admin"]}

# 头部设置 - 安全性和性能优化
[[headers]]
for = "/*"
[headers.values]
# 安全头部
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# 性能优化
Cache-Control = "public, max-age=3600"

# 静态资源缓存优化
[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# 字体文件缓存
[[headers]]
for = "*.woff"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# HTML 文件缓存策略（较短的缓存时间）
[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "public, max-age=3600"

# 压缩设置
[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

# 表单处理（如果需要联系表单）
# [forms]
#   spam_protection = true

# 函数设置（如果使用 Netlify Functions）
# [functions]
#   directory = "functions/"

# 插件配置
[[plugins]]
package = "@netlify/plugin-sitemap"

# 自定义域名设置（部署后配置）
# [[redirects]]
#   from = "https://warm-music.netlify.app/*"
#   to = "https://wenyin.music/:splat"
#   status = 301
#   force = true

# 环境变量（在 Netlify 控制台设置）
# MUSIC_API_KEY
# WEATHER_API_KEY
# ANALYTICS_ID